### ISSUE TITLE
请问是否可以通过以下方式实现自动屏蔽？

### ISSUE THREAD

**Issue by blackcatIan** [WittBulter/DungeonWatchDog#20]
由于我不是专精LUA不擅长改LUA源码。实验了一些API想到了一些方法，你参考一下是否可以实现。
如果可以实现的话，请修改实现一下，拜托了求你了，自动外挂实在太多了屏的手都累了，不断会有新号出现

执行以下代码
--进行一次搜索，这里的3指团本,是通过C_LFGList.GetAvailableCategories()得到的
C_LFGList.Search(3)
local numResults, resultIDTable = C_LFGList.GetSearchResults();
for k,v in pairs(resultIDTable) do
    local temptable = C_LFGList.GetSearchResultInfo(v);
    print("--------------------")
    print("name:  " .. temptable["name"])
    print("comment:   " .. temptable["comment"])
    print("leanderName:  "  .. temptable["leaderName"])
end

通过这个可以得到队伍名，队伍信息，队长名
方案1：可以的话直接根据玩家在插件里设置的关键字直接能“过滤”掉是最好
方案2：如果不能过滤的话，只能屏蔽，那么定时1分钟1次进行根据关键字扫描屏蔽队长leaderName，以对抗外挂自动生成新的账号开队

参考API
https://wow.gamepedia.com/API_C_LFGList.GetSearchResultInfo

**Comment by WittBulter** [comment]
你好，首先只能很遗憾的回答你，不能。

`GetSearchResultInfo` 等所有的 API 获取到的有关 `C_LFGList` 的用户信息都是枚举中的一个值，只是普通的数字，在你打印显示它们时，会去 `WOW` 的界面渲染引擎中将这个索引代表的用户名打印出来，也就是说，`Lua` 的插件层是不能获取到值，也就无法完成对比，从而无法屏蔽。

但是，`leaderName` 是除外的，也就是本插件的实现方式，通过对比 `leaderName` 来过滤队伍，这里已经监听了 `C_LFGList` 的部分事件来保持过滤，比如新的队伍创建，队伍更新，脱离组队等等。也就是你说的方法中的一部分，但是不能用屏蔽、定时器解决，也不能完全过滤，这里有几个历史原因。

--------

1. Lua 层的定时器只能 `todo`，不能作为服务端来屏蔽玩家。如果调用屏蔽接口是远远不够的，因为跨服屏蔽的人数在很短时间内就可以达到几百人，远超屏蔽上限。其他聊天屏蔽插件只是自己维护了一个 List 然后在聊天频道过滤掉这条消息而已。

2. `leaderName` 的查询是通过一个暴雪的组队服务器完成的，这个服务器的查询不是高可用的，或许是暴雪有意为之，大约每 5 - 10 个查询就会有一个是空白。这也是无法彻底按 `leaderName` 屏蔽的最大原因。

3. 如果做重试查询也是无效的，因为查询是基于玩家服务器缓存的，只要没有查到在几秒内都是无数据，直到缓存穿透之后，也就是玩家浏览一段时间的组队列表后才会有结果，此时另一部分玩家又会出现查询失败(新加入组队服务的)。

4. 暴雪在早期 (TBC 之前) 曾经开放过 whos 精准查询，后来发现服务器有 99% 资源在被插件滥用，甚至导致宕机，后来取消了精准查询。并且以后都不会再有。

5. 跨服组队的人数巨大，按我的统计来看，相当一部分用户会很快屏蔽 1000+ 的玩家，甚至有 5k+，这在客户端来说是相当大的数据量，每次过滤都需要检查是否命中，为了保证能够快速过滤必须使用 Hash (用空间换时间)，插件的内存消耗只会越来越高。大量的 CPU 工作也会使 Lua 占用太多的主线程导致渲染帧数下降。最重要的是 Lua 的内存释放并没有想象中的智能，如果频繁手动释放内存会导致严重的掉帧。(肉眼可见卡顿)



鉴于这几个原因，目前是无法实现 100% 屏蔽效果的插件，暴雪更是希望不要出现社区分裂，所以对接口也多做限制。
我曾经有一个想法是把屏蔽列表做成去中心化，每个玩家自动维护列表的一部分，当靠近另一个玩家时立刻通信同步列表再去除不活跃用户，最后在所有的玩家群体中存在一个当前活跃、不可见、每个人维护一部分的去中心化的屏蔽列表。最后由于需要大量的时间没有做。你或许可以试试这个想法。

希望对你有帮助。
